const translations = {
  es: {
    'brand.subtitle': 'Sistemas digitales para operaciones reales',
    'nav.services': 'Servicios',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'hero.eyebrow': 'Soluciones digitales para operación, control y trazabilidad',
    'hero.title': 'Sistemas elegantes para operaciones que exigen precisión, visibilidad y control.',
    'hero.text': 'Zenvik diseña plataformas digitales para empresas que necesitan transformar procesos complejos en experiencias simples, medibles y confiables.',
    'hero.cta1': 'Explorar servicios',
    'hero.cta2': 'Solicitar una conversación',
    'hero.metric1': 'Plataformas a la medida',
    'hero.metric2': 'Monitoreo en tiempo real',
    'hero.metric3': 'Trazabilidad operativa',
    'hero.panelLabel': 'Precisión operativa',
    'hero.cardTitle': 'Tecnología que se siente clara desde el primer vistazo.',
    'hero.cardText': 'Interfaces limpias, dashboards útiles y sistemas construidos para operar con confianza en entornos reales.',
    'services.label': 'Servicios',
    'services.title': 'Tres líneas de trabajo, una misma idea: simplificar operaciones complejas.',
    'services.web.title': 'Desarrollo Web Personalizado',
    'services.web.text': 'Plataformas web diseñadas para procesos internos, portales operativos, visualización de datos y herramientas que responden a la lógica real de tu negocio.',
    'services.web.li1': 'Arquitectura clara y escalable',
    'services.web.li2': 'Experiencia visual limpia y profesional',
    'services.web.li3': 'Módulos ajustados a cada flujo',
    'services.transport.title': 'Tracking GPS y Monitoreo en Tiempo Real',
    'services.transport.text': 'Sistemas para visualizar recorridos, eventos, desempeño y control operativo de flotas o transporte público con dashboards dinámicos y datos en vivo.',
    'services.transport.li1': 'Visualización GPS centralizada',
    'services.transport.li2': 'Dashboards ejecutivos y operativos',
    'services.transport.li3': 'Supervisión de rutas y equipos',
    'services.trace.title': 'Trazabilidad para Plantas de Proceso',
    'services.trace.text': 'Herramientas para capturar, controlar y visualizar en tiempo real la información de animales y productos en cada etapa del proceso, mejorando trazabilidad, control y continuidad operativa.',
    'services.trace.li1': 'Beneficio, desposte y acondicionamiento',
    'services.trace.li2': 'Soporte multiespecie',
    'services.trace.li3': 'Interfaces simples, web o desktop',
    'about.label': 'Sobre Zenvik',
    'about.title': 'Tecnología construida para verse bien, operar mejor y escalar contigo.',
    'about.text1': 'Zenvik combina claridad visual, ingeniería aplicada y entendimiento operativo para crear soluciones digitales que no solo se ven profesionales, sino que resuelven problemas reales.',
    'about.text2': 'Nuestro enfoque prioriza interfaces limpias, trazabilidad confiable, dashboards accionables y sistemas adaptados a la lógica de cada organización.',
    'cta.label': 'Zenvik',
    'cta.title': 'Si el proceso es complejo, el sistema debe hacerlo sentirse simple.',
    'cta.button': 'Hablemos',
    'footer.subtitle': 'Built for clarity and control',
    'footer.text': 'Soluciones digitales con una estética premium, enfocadas en trazabilidad, monitoreo y plataformas hechas a la medida.',
    'footer.services': 'Servicios',
    'footer.s1': 'Desarrollo web',
    'footer.s2': 'Tracking GPS',
    'footer.s3': 'Trazabilidad',
    'footer.contact': 'Contacto'
  },
  en: {
    'brand.subtitle': 'Digital systems for real operations',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.eyebrow': 'Digital solutions for operations, control, and traceability',
    'hero.title': 'Elegant systems for operations that demand precision, visibility, and control.',
    'hero.text': 'Zenvik designs digital platforms for organizations that need to turn complex processes into simple, measurable, and reliable experiences.',
    'hero.cta1': 'Explore services',
    'hero.cta2': 'Request a conversation',
    'hero.metric1': 'Custom platforms',
    'hero.metric2': 'Real-time monitoring',
    'hero.metric3': 'Operational traceability',
    'hero.panelLabel': 'Operational precision',
    'hero.cardTitle': 'Technology that feels clear from the very first glance.',
    'hero.cardText': 'Clean interfaces, useful dashboards, and systems designed to operate confidently in real-world environments.',
    'services.label': 'Services',
    'services.title': 'Three service lines, one idea: simplify complex operations.',
    'services.web.title': 'Custom Web Development',
    'services.web.text': 'Web platforms designed for internal processes, operational portals, data visualization, and business tools aligned with the real logic of your workflow.',
    'services.web.li1': 'Clear and scalable architecture',
    'services.web.li2': 'Clean and professional visual experience',
    'services.web.li3': 'Modules tailored to each workflow',
    'services.transport.title': 'GPS Tracking and Real-Time Monitoring',
    'services.transport.text': 'Systems to visualize routes, events, performance, and operational control for fleets or public transport through live dashboards and real-time data.',
    'services.transport.li1': 'Centralized GPS visibility',
    'services.transport.li2': 'Executive and operational dashboards',
    'services.transport.li3': 'Route and team supervision',
    'services.trace.title': 'Traceability for Processing Plants',
    'services.trace.text': 'Tools to capture, control, and visualize animal and product information in real time across each processing stage, improving traceability, control, and operational continuity.',
    'services.trace.li1': 'Slaughter, cutting, and conditioning',
    'services.trace.li2': 'Multi-species support',
    'services.trace.li3': 'Simple web or desktop interfaces',
    'about.label': 'About Zenvik',
    'about.title': 'Technology built to look refined, operate better, and scale with you.',
    'about.text1': 'Zenvik combines visual clarity, applied engineering, and operational understanding to create digital solutions that not only look professional, but solve real problems.',
    'about.text2': 'Our approach prioritizes clean interfaces, reliable traceability, actionable dashboards, and systems adapted to each organization’s operating logic.',
    'cta.label': 'Zenvik',
    'cta.title': 'If the process is complex, the system should make it feel simple.',
    'cta.button': 'Let’s talk',
    'footer.subtitle': 'Built for clarity and control',
    'footer.text': 'Premium digital solutions focused on traceability, operational monitoring, and tailored platforms.',
    'footer.services': 'Services',
    'footer.s1': 'Web development',
    'footer.s2': 'GPS tracking',
    'footer.s3': 'Traceability',
    'footer.contact': 'Contact'
  }
};

const buttons = document.querySelectorAll('.lang-option');
function applyLanguage(lang) {
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.dataset.i18n;
    if (translations[lang][key]) el.textContent = translations[lang][key];
  });
  buttons.forEach((btn) => btn.classList.toggle('active', btn.dataset.lang === lang));
}
buttons.forEach((btn) => btn.addEventListener('click', () => applyLanguage(btn.dataset.lang)));
applyLanguage('es');